name: Publish Image

on:
  push:
    branches:
    - main

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: create-release
        run: |
          docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest tag next-release --local --github

  build-linux:
    runs-on: ubuntu-latest
    needs:
      - release-version
    steps:
      - uses: actions/checkout@v1
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: do-build
        run: |
          docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest write-version latest
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: linux-artifacts
          path: target/release/clu

  build-mac:
    runs-on: macos-latest
    needs:
      - release-version
    steps:
      - uses: actions/checkout@v1
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
      - name: do-build
        run: |
          mkdir ~/bin
          curl --location https://github.com/ethankhall/crom/releases/download/v0.1.14/crom-mac.tar.gz | tar -xvz  -C ~/bin
          chmod +x ~/bin/crom
          ~/bin/crom write-version latest
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: mac-artifacts
          path: target/release/crom

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-mac
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: mac-artifacts
          path: artifacts/mac
      - uses: actions/download-artifact@v1
        with:
          name: linux-artifacts
          path: artifacts/linux
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        run: |
          docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest upload-artifacts latest --artifact-path=./artifacts linux mac
